### ISSUE TITLE
data

### ISSUE THREAD

**Issue by CarllllWang** [naganandy/G-MPNN-R#2]
Hello, I wonder how to get the unseen.txt, X.txt, and aux.txt of each external dataset such as JF17K for the task of link prediction, Thank you!

**Comment by naganandy** [comment]
Hi, thanks for the interest in the work. unseen.txt and aux.txt were constructed from the transductive versions using the method given in https://ojs.aaai.org//index.php/AAAI/article/view/4698. X.txt was constructed from the entity types.
